version: "3"

services:
  app:
    #build:
    #  context: .
    #  dockerfile: images/Dockerfile_nginx
    image: freeyland/magento-nginx:latest
    ports:
      - "80:8000"
      - "443:8443"
    links:
      - db
      - phpfpm
    volumes: &appvolumes
      - ~/.composer:/var/www/.composer:delegated
      - appdata:/var/www/html
      - sockdata:/sock
    depends_on:
      - phpfpm

  phpfpm:
    image: freeyland/magento-php:latest
    links:
      - db
    volumes: *appvolumes

  db:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-magento}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-magento}
      - MYSQL_USER=${MYSQL_USER:-magento}
      - MYSQL_PASS=${MYSQL_PASS:-magento}
    volumes:
      - dbdata:/var/lib/mysql
      #- ./mysqldata:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci --innodb-doublewrite=0

  redis:
    image: redis:5.0

  elasticsearch:
    image: elasticsearch:5.6
    ports:
      - "9200:9200"
      - "9300:9300"

  elastic-hq:
    image: elastichq/elasticsearch-hq
    ports:
      - "5000:5000"

  # Disabling cron by default as it uses higher CPU, enable if needed
  #cron:
  #  image: markoshust/magento-php:7.2-fpm-3
  #  user: root
  #  command: /usr/local/bin/cronstart
  #  tty: true
  #  links:
  #    - db
  #  volumes: *appvolumes

volumes:
  appdata:
  dbdata:
  sockdata:
