#!/bin/bash
DOMAIN=${1:-magento2.test}
VERSION=${2:-2.3.0}

curl -s https://raw.githubusercontent.com/freeyland/docker-magento/master/lib/template|bash -s - magento-2
echo "2"
bin/download $VERSION
echo "3"

bin/setup $DOMAIN
