#!/bin/bash
DOMAIN=${1:-magento2.test}
VERSION=${2:-2.3.0}


echo "A"
#curl -s https://raw.githubusercontent.com/freeyland/docker-magento/master/lib/template|bash -s
echo "B"
if [ $VERSION != "bypass" ]; 
then
bin/download $VERSION
fi

echo "C"
#bin/setup $DOMAIN
